"""
Generate the demo statement served at /sample-statement.csv.

Deterministic (fixed seed) so the demo numbers never drift between builds, and
entirely synthetic -- no real account, merchant relationship or person. It is
shaped like a real Indian bank export (banner preamble, DD/MM/YY dates, split
Withdrawal/Deposit columns, a trailing footer line) so loading it exercises the
auto-mapper rather than a tidy three-column file that proves nothing.

It deliberately contains:
  * five recurring series, so Subscriptions and Reconciliation have real work;
  * ONE genuinely missing gym charge, so the exception list has a true positive
    instead of an empty state;
  * ONE large one-off purchase, so Anomalies fires and the forecast can show
    what it excludes and why.

Regenerate with:  python scripts/make_sample_statement.py
"""
import datetime as dt
import random

OUT = "viewer/public/sample-statement.csv"
random.seed(20260902)

rows = []


def add(d, narration, withdrawal=None, deposit=None):
    rows.append((d, narration, f"{random.randint(10**8, 10**9 - 1)}", withdrawal, deposit))


MONTHS = [(2025, m) for m in range(1, 9)]          # Jan -> Aug 2025

for year, m in MONTHS:
    add(dt.date(year, m, 1),  "NEFT-DR-GREENVIEW APARTMENTS-RENT", 22000.00)
    add(dt.date(year, m, 3),  "UPI-NETFLIX ENTERTAINMENT-NETFLIX@YBL", 649.00)
    add(dt.date(year, m, 6),  "UPI-SPOTIFY INDIA-SPOTIFY@AXIS", 119.00)
    add(dt.date(year, m, 11), "UPI-JIO PREPAID RECHARGE-JIO@PAYTM", 399.00)
    # June's gym charge is deliberately absent: a real, explainable exception.
    if m != 6:
        add(dt.date(year, m, 17), "POS 4218XXXX9031 PULSE FITNESS", 1499.00)
    add(dt.date(year, m, 28), "SALARY CREDIT-ACME TECHNOLOGIES PVT LTD", None, 96000.00)

# Quarterly premium.
for m in (1, 4, 7):
    add(dt.date(2025, m, 21), "BILLPAY-SURAKSHA HEALTH INSURANCE", 3200.00)

# Everyday spending.
MERCHANTS = [
    ("UPI-SWIGGY ORDER-SWIGGY@ICICI", 160, 780),
    ("UPI-ZOMATO ONLINE-ZOMATO@PAYTM", 140, 690),
    ("UPI-BLINKIT GROCERY-BLINKIT@YBL", 210, 1480),
    ("POS 4218XXXX9031 BIGBASKET DAILY", 380, 2400),
    ("UPI-UBER INDIA SYSTEMS-UBER@AXIS", 85, 460),
    ("UPI-RAPIDO BIKE TAXI-RAPIDO@OKAXIS", 45, 190),
    ("UPI-AMAZON SELLER SVCS-AMAZON@APL", 240, 3100),
    ("UPI-MYNTRA DESIGNS-MYNTRA@HDFC", 600, 2900),
    ("UPI-THIRD WAVE COFFEE-TWC@OKHDFC", 130, 420),
    ("POS 4218XXXX9031 INDIAN OIL PETROL", 900, 2600),
    ("UPI-APOLLO PHARMACY-APOLLO@YBL", 120, 1150),
    ("ATM WDL 4218XXXX9031 INDIRANAGAR", 500, 3000),
]

d = dt.date(2025, 1, 1)
while d <= dt.date(2025, 8, 31):
    for _ in range(random.randint(1, 3)):
        name, lo, hi = random.choice(MERCHANTS)
        add(d, name, float(random.randint(lo, hi)))
    d += dt.timedelta(days=1)

# One large one-off: real money, but not a recurring pattern to project.
add(dt.date(2025, 5, 14), "UPI-CROMA ELECTRONICS-CROMA@ICICI", 78999.00)

rows.sort(key=lambda r: r[0])

balance = 184500.00
out = []
for d, narration, ref, w, dep in rows:
    balance = balance - (w or 0) + (dep or 0)
    out.append((d, narration, ref, w, dep, round(balance, 2)))

with open(OUT, "w", newline="", encoding="utf-8") as f:
    f.write("SAMPLE STATEMENT - SYNTHETIC DATA, NOT A REAL ACCOUNT\n")
    f.write("Generated by scripts/make_sample_statement.py for the ExpenseEye demo\n")
    f.write("Period: 01/01/2025 to 31/08/2025\n")
    f.write("\n")
    f.write("Date,Narration,Chq./Ref.No.,Value Dt,Withdrawal Amt.,Deposit Amt.,Closing Balance\n")
    for d, narration, ref, w, dep, bal in out:
        ds = d.strftime("%d/%m/%y")
        f.write(f"{ds},{narration},{ref},{ds},{w or ''},{dep or ''},{bal}\n")
    f.write("\n")
    f.write("*** End of Statement ***\n")

print(f"wrote {OUT}: {len(out)} transactions, {out[0][0]} -> {out[-1][0]}")
